### ISSUE TITLE
不更新的 hosts 弱爆了啊

### ISSUE THREAD

**Issue by alsotang** [highsea/Hosts#3]
你看我这实时更新的。

https://github.com/alsotang/alsohosts

**Comment by highsea** [comment]
额，谷歌 和 脸书 还能上，就不用更新了吧…… 唐少爷

**Comment by alsotang** [comment]
我们可以考虑把我们的 hosts 合并一下，一起提供在线版本的 hosts 服务嘛。

2015-08-04 13:45 GMT+08:00 高海 <notifications@github.com>:

**Comment by highsea** [comment]
可以挖，我等会儿 push 到你那儿， by huhamhire-hosts ~

**Comment by alsotang** [comment]
嗯嗯，写个脚本就合并了。合并到这里吧：https://github.com/alsotang/alsohosts/blob/master/domains.js

**Comment by alsotang** [comment]
其实我也用了 huhamhire-hosts，不知道我们两个的合并之后会增大多少的量，应该很多重复的。记得去个重哈。

**Comment by highsea** [comment]
出来了，高级啊， 这是自动从那里爬过来的 ip吧，[赞一个](http://images0.cnblogs.com/blog2015/531703/201508/041511532517492.png)

![](http://images0.cnblogs.com/blog2015/531703/201508/041511532517492.png)

**Comment by alsotang** [comment]
这个自动更新只要起个服务器就好了啊。

我的这个结果是在美国的服务器上解析出来的。

2015-08-04 15:14 GMT+08:00 高海 <notifications@github.com>:

**Comment by sibeily** [comment]
表示看不懂，大神们，来个简单明了可ctrl＋c，ctrl＋v的，可以吗

**Comment by alsotang** [comment]
http://t.cn/RLjSPjg  这里有

2015-08-04 18:16 GMT+08:00 sibeily <notifications@github.com>:

**Comment by highsea** [comment]
@sibeily  被你雷到了， 用这个吧 https://github.com/highsea/Hosts/blob/master/hosts 无脑复制黏贴就可以，唐少爷的东东还是有技术含量的 ^_^ ，唉~ 下班回家，改天好好研究下 高级的hosts
