### ISSUE TITLE
youtube不能看视频

### ISSUE THREAD

**Issue by syyjay** [highsea/Hosts#4]
youtube不能看视频

**Comment by highsea** [comment]
请使用 https://github.com/racaljk/hosts/blob/master/hosts 这个项目更新吧

**Comment by syyjay** [comment]
更新 也不能看 之前 就用的 这个

**Comment by highsea** [comment]
那就木有办法了，试试 自己买个国外的 VPS 玩玩吧～ 然后贡献下代理

**Comment by syyjay** [comment]
好的 谢谢
